abstract class AppStates {}
class AppInitialState extends AppStates{}
class AppChangePageState extends AppStates{}
class AppCreateDataBaseState extends AppStates{}
class AppGetDataBaseState extends AppStates{}
class AppUpdateDataBaseState extends AppStates{}
class AppInsertToDataBaseState extends AppStates{}
class AppChangeSheetShowState extends AppStates{}
class AppGetLoadingState extends AppStates{}
